[package]
name = "apple-ptrace-test"
version = "0.1.0"
authors = ["xd009642 <danielmckenna93@gmail.com>"]

[dependencies]
mach = "0.2.2"
nix = { git = "https://github.com/xd009642/nix", branch = "issue-947"} 
